services:
  n8n:
    image: n8nio/n8n:latest
    container_name: n8n
    environment:
      - GENERIC_TIMEZONE=Europe/Amsterdam
      - NODE_ENV=production
      - N8N_SECURE_COOKIE=false
      - N8N_HOST=${N8N_HOST}
    ports:
      - "5678:5678"
    volumes:
      - ${N8N_DATA}:/home/node/.n8n
    restart: unless-stopped

volumes:
  n8n_data:
    name: n8n_data
